export default [
  "Hello Ngân !!!",
  "Khi em đọc được những dòng chữ này!!!",
  "Chắc cũng là lúc...",
  "Chúng ta lại sắp phãi xa nhau",
  "Anh biết rằng cả em và anh...",
  "Đều hiểu rằng! lời chia tay kia chỉ là một thứ gì đó vô hình",
  "Nó không là gì cả!!!",
  "Vì vốn dĩ tình cảm của anh và em dành cho nhau vẫn vậy!!!",
  "Phãi không???",
  "Em không phãi là người đầu tiên đến với anh!!!",
  "Và anh cũng vậy, cũng không phãi người đầu tiên với em!!!",
  "Nhưng chắc có lẽ,em là người mà a dành chọn tình cảm!!!",
  "Tình cảm đó không đơn thuần của tuổi mới lớn",
  "Cũng không phãi của tuổi trẻ bồng bột ngoài kia",
  "Mà thực sự nó là 1 thứ tình cảm gì đó thiêng liêng",
  "Dành cho nhau những gì tuyệt vời nhất",
  "Lo lắng cho nhau,",
  "Hay thậm chí là cảm nhận thấy nỗi đau của đối phương.",
  "Nếu vô tình có ai đó hỏi anh, mô tả người yêu của anh?",
  "Thì anh sẻ mô tả ngắn gọn như này!!! em thấy được không???",
  "Lùn tịt, xấu tính, đôi khi rất trẻ con, lại còn lì nữa,tóm lại là xấu đều!!!",
  "Nhưng mà, vậy là đủ với tuôi, vì tuôi yêu những cái vừa nêu trên của cô ấy.",
  "Còn nếu ai mà hỏi em, chắc tả anh tệ hết sức tệ là cái chắc rồi !!!",
  "Khi 2 ta quen nhau, không những anh, mà ắc hẵn là em,",
  "Đã trải qua nhiều thứ cảm xúc",
  "Có buồn, vui, giận , hờn , lo lắng ...",
  "Nhưng cũng nhờ những gia vị đó mà anh mới biết được Yêu thật sự là như nào!",
  "Đôi khi nó làm cho anh nhớ em đến điên đầu!!!",
  "Chỉ biết rằng trong đầu anh tất thẩy chỉ là em.",
  "Lúc ị khó mà cũng không thể quên được nữa huống chi là?",
  "hihi,a đùa thôi!!!",
  "Chứ thực tế nó vẫn là vậy :v",
  "Năm mới vừa rồi a không chúc em đó là bởi",
  "Anh sợ rằng những lời chúc đó a mong rằng anh sẽ là người cùng em làm nên",
  "Những lời nhắc nhở mong em sau này ra sao đó!!!",
  "Anh mong rằng chính anh là người bên cạnh em lúc em trưởng thành hay thay đổi!!! ",
  "Anh sẽ luôn ở cạnh em!!! ",
  "Anh rất giỏi việc im lặng,",
  "Vậy nên sẽ không phiền chút nào khi cứ để anh im lặng ở canh em,",
  "Cho đến khi có người đến cạnh em thay anh làm việc đó,",
  "Lúc đó mới là lúc thật sự anh an tâm xa em,",
  "Đối với anh,"
  "Cảm giác bình yên và chậm lại thật sự nhất vẫn là lúc ở cạnh em,",
  "Một cảm giác khó tả mà khiến cho anh cảm thấy trân trọng từng giây,",
  "từng phút",
  "lúc nào cũng phãi e sợ nhìn đồng hồ còn bao lâu nữa,",
  "Đôi lúc a còn có suy nghĩ ích kỉ,...",
  "Muốn cột em lại với anh, để 2 ta không phãi xa nhau!",
  "Để lúc nào anh cũng được gần em,cùng em làm mọi thứ.",
  "Nhưng có lẽ điều đó là không thể",
  "Thức dậy mỗi sáng cùng em",
  "không thể?",
  "Chở em đi học!",
  "Không thể?",
  "Cùng em nấu ăn!",
  "Không thể?",
  "Đánh em mỗi lúc em không nghe lời!",
  "Không thể?",
  "Lo lắng cho em lúc em ốm đau!",
  "Không thể?",
  "Cho em cảm giác có người yêu bên cạnh",
  "Không thể?",
  "Tất cả mọi điều a đều không thể làm cho em.",
  "Đôi lúc a cảm thấy bất lực, vô vọng.",
  "Vì nhìn em phãi chịu thiệt thòi như vậy",
  "Nhưng từ tận sau thâm tâm anh",
  "Điều anh có thể duy nhất đó chính là...",
  "YÊU EM, bằng tất cả những gì anh đang có...",
  "Anh xin lỗi những lúc trách lầm em...",
  "Xin lỗi vì trả lời chậm tin nhắn của em.",
  "Tại anh sợ rằng làm không kịp,",
  "Rồi không thể nói ra hết những tâm tư tình cảm này,",
  "Liệu em có giận anh không?",
  "Có thì anh xin lỗi người đẹp nhe!!!",
  "Người phụ nữ mà anh yêu thương đẹp nhứt trong mắt anh,",
  "Không cần trong mắt người khác đâu,",
  "Thấy đẹp rồi cưỡm em mất khỏi anh nữa thì mệt",
  "kakaka",
  "Nói vậy thôi, không nói nữa .",
  "A chỉ mong rằng năm mới này em sẽ làm được những điều em muốn.",
  "Sống cho em!",
  "Trưởng thành hơn,",
  "Tập thê dục nhiều hơn để mông bớt xệ.",
  "Chắc đến đây cũng hiểu hết ý anh rồi nên anh hông nói nữa nhoe!!!",
  "Bái bai mặc nọng lái laiiii Ngân sờ tu pịc của anh!!!",
];
